# Generated by Django 4.2.4 on 2023-08-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbBoard',
            fields=[
                ('board_seq', models.DecimalField(decimal_places=65535, max_digits=65535, primary_key=True, serialize=False)),
                ('board_title', models.CharField(max_length=30)),
                ('board_content', models.CharField(blank=True, max_length=20, null=True)),
                ('board_writer', models.CharField(max_length=40)),
                ('board_password', models.CharField(max_length=80)),
                ('create_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'tb_board',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbComment',
            fields=[
                ('comment_detail_seq', models.DecimalField(decimal_places=65535, max_digits=65535, primary_key=True, serialize=False)),
                ('comment_depth', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('comment_title', models.CharField(max_length=40)),
                ('comment_writer', models.CharField(max_length=40)),
                ('comment_password', models.CharField(max_length=40)),
                ('create_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'tb_comment',
                'managed': False,
            },
        ),
    ]
